    name: gabagoolshopbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OZON_CLIENT_ID
        sync: false
      - key: OZON_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: RENDER
        value: true
